class JobError(Exception):
	pass
class TestError(Exception):
	pass
